stages:
  - test

default:
  before_script:
    - apt-get update
    - apt-get install -y gnupg2
    #
    - curl -fsSL https://packages.couchbase.com/clients/c/repos/deb/couchbase.key | apt-key add
    - echo "deb https://packages.couchbase.com/clients/c/repos/deb/debian10 buster buster/main" > /etc/apt/sources.list.d/couchbase.list
    - apt-get update
    - apt-get install -y libcouchbase-dev libzip-dev git libmemcached-dev
    - docker-php-ext-install zip
    #
    - mkdir -p /usr/src/php/ext/xdebug && curl -fsSL https://pecl.php.net/get/xdebug | tar xvz -C "/usr/src/php/ext/xdebug" --strip 1
    - docker-php-ext-install xdebug
    - echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    #
    - mkdir -p /usr/src/php/ext/couchbase
    - curl -fsSL https://pecl.php.net/get/couchbase | tar xvz -C "/usr/src/php/ext/couchbase" --strip 1
    - docker-php-ext-install couchbase
    #
    - mkdir -p /usr/src/php/ext/memcached
    - curl -fsSL https://pecl.php.net/get/memcached | tar xvz -C "/usr/src/php/ext/memcached" --strip 1
    - docker-php-ext-install memcached
    #
    - mkdir -p /usr/src/php/ext/redis
    - curl -fsSL https://pecl.php.net/get/redis | tar xvz -C "/usr/src/php/ext/redis" --strip 1
    - docker-php-ext-install redis
    #
    - mkdir -p /usr/src/php/ext/apcu
    - curl -fsSL https://pecl.php.net/get/apcu | tar xvz -C "/usr/src/php/ext/apcu" --strip 1
    - docker-php-ext-install apcu
    #
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install

php8:
  stage: test
  image: php:8-cli
  cache:
    key: php8
    paths:
      - ./vendor
  script:
    - ./vendor/bin/phpcs --extensions=php --standard=PSR12 --ignore=*/_files/* src/ tests/
#    - ./vendor/bin/phpmd ./src text ./phpmd.xml --suffixes php   ## Broken in php 8.  Bug is filed upstream: https://github.com/phpmd/phpmd/issues/853
    - ./vendor/bin/phpstan -n --no-ansi analyse --no-progress --level=5 src/
    - ./vendor/bin/phpunit tests/ --coverage-clover clover.xml
    - bash <(curl -s https://codecov.io/bash)
